### PR TITLE
bump deps for node 4.2 support

### LINKED ISSUE #45: Install fails on Node 4.*
Some of the dependencies fail on install with the latest versions of node. Seems as this is coming from `JSDom` which has already resolved this issue on the latest version.

full error https://gist.github.com/mattmischuk/553e359d3157dca2a0ed

### PR DESCRIPTION
**Pull request by qrohlf**
(fingers crossed)

resolves #45 if it works

### CODE REVIEW

**Comment by qrohlf** [comment]
Travis appears to be having issues with Cairo

**Comment by qrohlf** [comment]
breakfast-club-jud-fist-pump

**Comment by jme783** [comment]
@qrohlf any update on Travis? I'm seeing tons of unnecessary output when I don't want `cairo` to be installed at all. I'm seeing output like this:
```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/travis/.nvm/versions/node/v4.2.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.13.0-40-generic
gyp ERR! command "/home/travis/.nvm/versions/node/v4.2.2/bin/node" "/home/travis/.nvm/versions/node/v4.2.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/travis/build/spark/device-setup/node_modules/livereactload/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
```

The build continues, but is there any way to avoid attempted installation?

**Comment by qrohlf** [comment]
https://docs.npmjs.com/cli/install

> The npm install --no-optional argument will prevent optional dependencies from being installed.

**Comment by jme783** [comment]
@qrohlf thanks!

**Pull request merged**
