### PR TITLE
Fixed: TypeError: Cannot read property 'canvas' of undefined

### PR DESCRIPTION
**Pull request by xaionaro**
The error occured on NodeJS8 on MacOS Mojave with canvas2.0

### CODE REVIEW

**Comment by qrohlf** [comment]
I’m not sure how you got a node-canvas 2.x dependency in your stack, since the package.json explicitly wants node-canvas 1.x?

**Comment by stevewillard** [comment]
I'm seeing the same issue on Node 11.9 on Mojave

**Comment by qrohlf** [comment]
@stevewillard can you verify that you've got a compatible (1.x) version of node-canvas installed?

**Comment by stevewillard** [comment]
Ah, I realized that I had a `canvas` version `2.x.x` in the dependencies for some reason. I removed it and it works now! Thanks.

**Comment by xaionaro** [comment]
OK. I close this because there's no time to refresh in memory why did I need canvas 2.x.

At least other people can see this ticket and understand this problem now (if they meet it).

**Comment by qrohlf** [comment]
I’ll add support for 2.x and probably just drop support for 1.x in the next major version of Trianglify, this PR is going to be useful as a reference. Thanks for taking the time!

**Pull request closed without merging**
