### PR TITLE
Extract point generation

### PR DESCRIPTION
**Pull request by enzuguri**
Enables specifying a custom array of points (see the custom-points-example.html) for users who may want to provide their own point generation.

Additionally, I refactored the code required to generate points to inline the _map function for performance reasons, this jsbin highlights the difference:
http://jsbin.com/helihu/4/edit?js,output

One of these commits includes a test to validate that the optimization produces the same result, it is then subsequently removed in a further commit. I leave this in the history in case a re-validation is required.

### CODE REVIEW

**Comment by qrohlf** [comment]
just FYI this hasn't dropped off my radar, hoping to get around to reviewing it soon!

**Comment by qrohlf** [comment]
@enzuguri looks great, and that performance improvement is HUGE. Thanks a ton for this.

**Comment by nadbm** [comment]
@qrohlf This feature is in the master branch, but the version and npm doesn't reflect this. Any plans to do this soon? 
Thanks!

**Comment by qrohlf** [comment]
@nadbm @enzuguri @flexzuu heads-up that this is finally released in v1.0.1.

**Comment by enzuguri** [comment]
Awesome, thanks! I have two more branches I'm toying with, one speeds up generating triangles, and one allows a custom render function (with a d3 example). Hope to have some more PR's for you when life allows.

**Pull request merged**
