### PR TITLE
Extract point generation

### PR DESCRIPTION
**Pull request by enzuguri**
Enables specifying a custom array of points (see the custom-points-example.html) for users who may want to provide their own point generation.

Additionally, I refactored the code required to generate points to inline the `_map` function for performance reasons, this jsbin highlights the difference:
http://jsbin.com/helihu/4/edit?js,output

One of these commits includes a test to validate that the optimization produces the same result, it is then subsequently removed in a further commit. I leave this in the history in case a re-validation is required.

### CODE REVIEW

**Comment by qrohlf** [comment]
First of all, thanks for this. It sounds like you put a lot of work into it and I appreciate the performance improvements. Unfortunately, I think something went wrong with the PR and you've got over a year of commit history in the diff, which makes it really hard for me to review. Maybe try rebasing and force pushing to see if that fixes it?

**Comment by enzuguri** [comment]
Hi @qrohlf, yes I thought it was a bit off. In your contributing guide (contributing.md) you mention that PR should have the target branch of `gh-pages`, which probably explains the massive diff. I can edit this to point to master should you require?

**Comment by qrohlf** [comment]
Oops, that's an outdated doc from when the documentation and the library were the same codebase. You'll want to re-open the PR against master and then everything should be good.

+1 for reading the docs... sorry that they were wrong 😬

**Comment by qrohlf** [comment]
(I'll update the CONTRIBUTING file now)

**Pull request closed without merging**
