### PR TITLE
Added Optional Stroke Colour

### PR DESCRIPTION
**Pull request by EpicKris**
This solves part of issue #84.

### CODE REVIEW

**Comment by EpicKris** [comment]
#88

**Comment by qrohlf** [comment]
Thanks for this, seems reasonable to me!

I’m currently traveling without a laptop, but I can merge this and cut a release when I’m back (mid-september)

**Comment by qrohlf** [comment]
Hey! Sorry about the delay, this one fell through the cracks. Code looks good but it needs a rebase before I can merge it.

**Comment by EpicKris** [comment]
What do I need to do for that?

**Comment by qrohlf** [comment]
Basically, the code you changed also had changed as part of a different PR, so git can no longer merge your PR automatically. I prefer to use a rebase to solve this, which is a way of making git act as though you made your changes to the most recently updated version of the file. 

This is a pretty good overview of how rebasing works in git: https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase

If you run into issues, I can do the rebase manually when I’ve got time for it.

**Pull request closed without merging**
