### PR TITLE
Replace delaunay-fast with delaunator

### PR DESCRIPTION
**Pull request by jhwohlgemuth**
- Install delaunator
- Replace uglify with babel-minify to support ES6 minification
- Remove un-used dependencies
- Add lock file (npm v5)

### CODE REVIEW

**Comment by jhwohlgemuth** [comment]
Considering the difficulty of testing a library that generates random images...here is a proof of life:

proof-of-life

**Comment by qrohlf** [comment]
Diff looks great, thanks for the minification/dep versioning work too. Will spin this up and do some quick benchmarks tomorrow or tues, then merge.

I'll probably be versioning this as `1.2.0` unless you can think of any reason why delaunator would merit a major version bump instead.

**Comment by jhwohlgemuth** [comment]
@qrohlf Awesome. What benchmarks do you perform? Are they something that could be automated and/or added to the project? 

Regarding the minor version: seems reasonable to me since the API is unchanged and therefore backwards compatible.

**Comment by qrohlf** [comment]
@jhwohlgemuth hey, sorry about the delay on this. Haven't had a lot of spare time for OSS lately. 

I just got around to testing this, it seems like the perf bump is negligible but this branch actually produces better results where the polygon vertices meet (fewer overlaps). 

```
running perf test on master
took 3945.0355560183525ms to complete
took 3806.520805954933ms to complete
took 3794.975149989128ms to complete


running perf test on jhwohlgemuth:feature/replace-delaunay-implementation
took 3290.6688849925995ms to complete
took 3227.9227900505066ms to complete
took 3283.33089697361ms to complete


running diff test
stability check on v1... PASS
stability check on v2... PASS
diff check... FAIL
output written to disk for visual inspection
stability check on v1... PASS
stability check on v2... PASS
diff check... FAIL
output written to disk for visual inspection
```

**Pull request merged**
