### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by mattmischuk**
This resolves issues from other dependencies when doing an `npm install` on node 4.1.1.

### CODE REVIEW

**Comment by qrohlf** [comment]
This is kind of a tricky issue because jsdom was very *opinionated* about the whole io.js/node.js thing, so bumping the jsdom version breaks compatibility for all versions of node < 4.0.

I'm okay with this, but you'll need to update the supported node versions in the `travis.yml` config so that the tests pass.

**Comment by mattmischuk** [comment]
@qrohlf looks like the tests aren't passing with the latest JSDOM API. Do still want me to work from this branch?

**Comment by qrohlf** [comment]
Interesting. Breaking changes in jsDom, I guess? If you want to try to tackle getting trianglify working with node 4.1.1, go for it. I would normally do it myself, but my company has a big conference (FutureStack) we're hosting in mid-November so things are really busy for me right now in preparation. I likely will not have time to hack on Trianglify until after FutureStack.

**Comment by qrohlf** [comment]
I finally did some investigation into why things are failing for the node version bump: https://github.com/qrohlf/trianglify/issues/45#issuecomment-153574560

Basically, Trianglify won't be able to support Node 4.x until it's dependencies do. Hopefully that will happen soon!

**Comment by qrohlf** [comment]
Closed - implemented in #48

**Pull request closed without merging**
